<div class="container-fluid h-100">
    <div class="row h-100">

        <div class="col-md-6 banner">
            <div class="row h-100 justify-content-center align-items-center">
                <div>
                    <div class="communicationItem">
                        <i class="fas fa-search fa-2x mr-3"></i>
                        Siga o que lhe interessa.
                    </div>
                    <div class="communicationItem">
                        <i class="fas fa-user-friends fa-2x mr-3"></i>
                        Saiba sobre o que as pessoas estão falando.
                    </div>
                    <div class="communicationItem">
                        <i class="far fa-comment fa-2x mr-3"></i>
                        Participe da conversa.
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6 pt-4 pl-5 pr-5">
            <form method="post" action="/autenticar">
                <div class="row">
                    <div class="col-md-4 btnM mt">
                        <input type="text" class="form-control" placeholder="E-mail" name="email">
                    </div>
                    <div class="col-md-4 mt">
                        <input type="password" class="form-control" placeholder="Senha" name="senha">
                    </div>
                    <div class="col-auto mt">
                        <button type="submit" class="btn btn-primary mb-2">Entrar</button>
                    </div>
                </div>

                <!-- Mensagem de erro caso login seja invalido -->
                <?php if ($this->view->login == 'erro') { ?>
                    <div class="row erro1"> <!-- Inicio da div de erro -->
                        <div class="col">
                            <span class="text text-danger">*E-mail e ou senha inválido(s)</span>
                        </div>
                    </div> <!-- Fim da div de erro -->
                <?php } ?>

            </form>
            <div class="row pt-5 pl-5 pr-5">
                <div class="col pl-5 pr-5">
                    <div class="infos">
                        <img src="/img/twitter_logo.png" />
                        <h1 class="title">Veja o que está acontecendo <br> no mundo agora</h1>
                        <h2 class="mt-5 subtitle">Participe hoje do Twitter.</h2>
                        <a href="/inscreverse" class="btn btn-primary btn-block mb-2 btn-espaco">Inscrever-se</a>
                    </div>
                </div>
            </div>


        </div>

    </div>
</div>