<link rel="stylesheet" href="cadastro.css">
<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <a href="#"><img src="/img/twitter_logo.png" /></a>
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">

            <form action="/registrar" method="post"> <!-- Envia os dados do formulario para /registrar (metodo post não exibe os dados na url) -->
              <div class="form-group mb-3">
                <input type="text" class="form-control" placeholder="Nome" name="nome" value="<?php echo $this->view->usuario['nome'] ?>"> <!-- Essa linha de codigo php faz o campo receber e não perder o valor digitado caso aja um erro -->
              </div>

              <div class="form-group mb-3">
                <input type="text" class="form-control" placeholder="E-mail" name="email" value="<?php echo $this->view->usuario['email'] ?>">
              </div>

              <div class="form-group mb-3">
                <input type="password" class="form-control" placeholder="Senha" name="senha" value="<?php echo $this->view->usuario['senha'] ?>">
              </div>

              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block btn-inscrever">Inscrever-se</button>

              <?php if ($this->view->erroCadastro) { ?> <!-- Verificar se existe o paramento erroCadastro -->
                <small class="form-text text-danger">*Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente.</small>
              <?php } ?> <!-- Fim do bloco php -->

            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>